# Generated by Django 5.0.6 on 2024-08-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0002_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="page",
            name="repeat",
        ),
        migrations.AddField(
            model_name="page",
            name="countdown",
            field=models.IntegerField(default=21),
        ),
    ]
