# Generated by Django 5.0.6 on 2024-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0003_remove_page_goal_remove_page_repeat_page_countdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="goal_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Per Day"),
                    ("weekly", "Per Week"),
                    ("monthly", "Per Month"),
                ],
                default="daily",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="goal_units",
            field=models.CharField(
                choices=[("mins", "Minutes"), ("times", "Times")],
                default="mins",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="goal_value",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="page",
            name="habit_type",
            field=models.CharField(
                choices=[("good", "Good Habit Built"), ("bad", "Bad Habit Broken")],
                default="good",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("interval", "Interval"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
    ]
