# Generated by Django 5.0.6 on 2024-08-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "habit_builder",
            "0004_page_goal_frequency_page_goal_units_page_goal_value_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="countdown",
        ),
        migrations.RemoveField(
            model_name="page",
            name="goal_frequency",
        ),
        migrations.RemoveField(
            model_name="page",
            name="goal_units",
        ),
        migrations.RemoveField(
            model_name="page",
            name="goal_value",
        ),
        migrations.RemoveField(
            model_name="page",
            name="habit_type",
        ),
        migrations.RemoveField(
            model_name="page",
            name="reminders",
        ),
        migrations.RemoveField(
            model_name="page",
            name="repeat",
        ),
        migrations.RemoveField(
            model_name="page",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="page",
            name="time_of_day",
        ),
        migrations.AddField(
            model_name="page",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="cover_images/"),
        ),
    ]
