# Generated by Django 5.0.6 on 2024-08-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0006_page_publish_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habit_name", models.CharField(max_length=100)),
                ("time_of_day_to_perform", models.TimeField()),
                ("start_date_of_habit", models.DateField()),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("interval", "Interval"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("countdown", models.IntegerField(default=21)),
                ("goal_value", models.IntegerField(default=0)),
                (
                    "goal_units",
                    models.CharField(
                        choices=[("mins", "Minutes"), ("times", "Times")],
                        default="mins",
                        max_length=10,
                    ),
                ),
                (
                    "goal_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Per Day"),
                            ("weekly", "Per Week"),
                            ("monthly", "Per Month"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "Page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit_builder.page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
