# Generated by Django 5.0.6 on 2024-08-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0007_habits"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="custom_goal_unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="habits",
            name="goal_units",
            field=models.CharField(
                choices=[
                    ("mins", "Minutes"),
                    ("times", "Times"),
                    ("other", "Any other unit"),
                ],
                default="mins",
                max_length=10,
            ),
        ),
    ]
