# Generated by Django 5.0.6 on 2024-08-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0008_habits_custom_goal_unit_alter_habits_goal_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="goal_units",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mins", "Minutes"),
                    ("times", "Times"),
                    ("other", "Any other unit"),
                ],
                default="mins",
                max_length=10,
                null=True,
            ),
        ),
    ]
