# Generated by Django 5.0.6 on 2024-08-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0009_alter_habits_goal_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time_of_day_to_perform",
            field=models.CharField(
                choices=[
                    ("anytime", "Anytime"),
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                ],
                default="anytime",
                max_length=10,
            ),
        ),
    ]
