# Generated by Django 5.0.6 on 2024-09-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0010_alter_habits_time_of_day_to_perform"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="interval_days",
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name="habits",
            name="last_completed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
