# Generated by Django 5.0.6 on 2024-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0012_remove_habits_interval_days_alter_habits_repeat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habits",
            name="last_completed_date",
        ),
        migrations.AddField(
            model_name="habits",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
