# Generated by Django 5.0.6 on 2024-09-06 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0014_habits_last_completed_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habits",
            name="completed",
        ),
    ]
