# Generated by Django 5.0.6 on 2024-09-06 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0015_remove_habits_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habit_name", models.CharField(max_length=100)),
                ("start_date_of_habit", models.DateField()),
                (
                    "Page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit_builder.page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
