# Generated by Django 5.0.6 on 2024-09-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0016_badhabit"),
    ]

    operations = [
        migrations.AddField(
            model_name="badhabit",
            name="succeed",
            field=models.BooleanField(default=False),
        ),
    ]
