# Generated by Django 5.0.6 on 2024-09-15 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0017_badhabit_succeed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badhabit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
