# Generated by Django 5.0.6 on 2024-09-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0022_note2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note2",
        ),
        migrations.AddField(
            model_name="note",
            name="page",
            field=models.CharField(default="page2", max_length=10),
        ),
    ]
