# Generated by Django 5.0.6 on 2024-09-22 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habit_builder", "0023_delete_note2_note_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="page",
        ),
    ]
